#!/usr/bin/python

import os

def setup_install():
  os.system('yum install python-pip -y') 
  os.system('pip install virtualenv')
  os.system('pip install --upgrade pip') 
  os.mkdir('/opt/django')
  os.chdir('/opt/django')
  os.system('yum install epel-release -y') 
  os.system('yum install python34 -y') 
  os.system('virtualenv -p python3 django')     
  
def install_django():
  os.chdir('/opt/django/django')
  os.system('source /opt/django/django/bin/activate && pip install django')
  os.system('source /opt/django/django/bin/activate && django-admin startproject project1')
  os.system('chown -R carlosaguilar1928 /opt/django/*')
  
def allowed_host():
  os.system('myip=$( curl https://api.ipify.org )' + \
            '&& sed -i "s/ALLOWED_HOSTS = \[\]/ALLOWED_HOSTS = \['"$myip"'\]/g" /opt/django/django/project1/project1/settings.py')
  
def start_django():
  os.system('sudo -u carlosaguilar1928 -E sh -c "source /opt/django/django/bin/activate && ' + \
            '/opt/django/django/project1/manage.py runserver 0.0.0.0:8000&"')
  os.system('yum install git -y')
 
setup_install()
install_django()
allowed_host()
start_django()
  
