#!/usr/bin/python

import os

def setup_install():
  os.system('yum install -y python-pip') 
  os.system('pip install -y virtualenv')
  os.system('pip install --upgrade pip -y') 
  os.mkdir('/opt/django')
  os.chdir('/opt/django')
  os.system('yum install -y epel-release') 
  os.system('yum install -y python34 python-pip') 
  os.system('virtualenv -p python3 django')     #run python3 in our virtual env
  os.chdir('/opt/django/django')
  os.system('source /opt/django/django/bin/activate')

def install_django(): 
  os.system('pip install -y django') 
  os.system('django-admin --version') 
  os.system('django-admin startproject project1')
  os.system('chown -R carlosaguilar1928 django')
  
#def allowed_host():
#  os.system('myip=$( curl https://api.ipify.org ) && sed -i "s/ALLOWED_HOSTS = \[\]/ALLOWED_HOSTS = \[\ '"$myip"\'/g" /opt/django/django/project1/project1/setting.py
 
def start_django():
  os.system('sudo su -u -carlosaguilar1928 && source /opt/django/django/bin/activate')
  os.sytem('/opt/django/project1/manage.py runserver 0.0.0.0:8000&')
  
  
 
setup_install()
install_django()
#allowed_host()
start_django()
  
